/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.CategoryController;
import controller.OrderController;
import controller.OrderProductController;
import controller.ProductController;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Category;
import model.Order;
import model.OrderProduct;
import model.Product;

/**
 *
 * @author Admin
 */
public class OrderProductFrm extends javax.swing.JDialog {

    /**
     * Creates new form OrderProductFrm
     */
    
    DefaultTableModel tableModelOrderProduct;
    
    List<OrderProduct> productOrderList = new ArrayList<>();
    List<Category> categoryList = new ArrayList<>();
    List<Product> productList = new ArrayList<>();
    
    int user_id;
    
    public OrderProductFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tableModelOrderProduct = (DefaultTableModel) tableOrderProduct.getModel();
        
        tableOrderProduct.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                int selectedIndex = tableOrderProduct.getSelectedRow();
                OrderProduct orderProduct = productOrderList.get(selectedIndex);
                
//                txtNameOrderPrd.setText(orderProduct.getUser_name());
//                boxProduct.setSelectedItem(orderProduct.getProduct_name());
//                boxNameCat.setSelectedItem(orderProduct.getCategory_name());
//                txtPriceOrderPrd.setText(orderProduct.getPrice());
//                txtCountOrderPrd.setText(String.valueOf(orderProduct.getCount()));
//                
//                btnDeleteOrderPrd.setEnabled(true);
//                btnUpdateOrderPrd.setEnabled(true);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        
        });
        
//        showComboBox_Category();
//        showComboBox_Product();
    }
    
//    public void showComboBox_Category() {
//        DefaultComboBoxModel<String> comboBoxModelOrderProduct = (DefaultComboBoxModel<String>) boxNameCat.getModel();
//        comboBoxModelOrderProduct.removeAllElements();
//        categoryList = CategoryController.findAll();
//        categoryList.forEach(category -> {
//            comboBoxModelOrderProduct.addElement(category.getName());
//        });
//    }
    
//    public void showComboBox_Product() {
//        DefaultComboBoxModel<String> comboBoxModelOrderProduct = (DefaultComboBoxModel<String>) boxProduct.getModel();
//        comboBoxModelOrderProduct.removeAllElements();
//        productList = ProductController.findAll();
//        productList.forEach(prd -> {
//            comboBoxModelOrderProduct.addElement(prd.getTitle());
//        });
//    }
//    
//    public void showComboBox_Product_findByCat(String name_cat) {
//        DefaultComboBoxModel<String> comboBoxModelOrderProduct = (DefaultComboBoxModel<String>) boxProduct.getModel();
//        comboBoxModelOrderProduct.removeAllElements();
//        productList = ProductController.findByCat(name_cat);
//        productList.forEach(prd -> {
//            comboBoxModelOrderProduct.addElement(prd.getTitle());
//        });
//    }
    
    private void showOrderProduct(int user_id) {
        productOrderList = OrderProductController.findAll(user_id);
        tableModelOrderProduct.setRowCount(0);
        
        productOrderList.forEach((prd) -> {
            tableModelOrderProduct.addRow(new Object[] {
                tableModelOrderProduct.getRowCount() + 1,
                prd.getUser_name(),
                prd.getProduct_name(),
                prd.getCategory_name(),
                prd.getPrice(),
                prd.getCount()
            });
        });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrderProduct = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableOrderProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên khách hàng", "Tên sản phẩm", "Tên danh mục", "Giá tiền", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(tableOrderProduct);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderProductFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderProductFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderProductFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderProductFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OrderProductFrm dialog = new OrderProductFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableOrderProduct;
    // End of variables declaration//GEN-END:variables

   void getUser_id(Order order) {
        user_id = order.getUser_id();
        showOrderProduct(user_id);
    }

}
